# Generated by Django 6.0 on 2026-01-01 16:56

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="name"),
                ),
            ],
            options={
                "verbose_name_plural": "categories",
            },
            managers=[
                ("objects", apps.core.models.SoftDeleteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="task",
            managers=[
                ("objects", apps.core.models.SoftDeleteManager()),
            ],
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("DEV", "Dev"),
                    ("TEST", "Test"),
                    ("STUCK", "Stuck"),
                    ("COMP", "Comp"),
                ],
                default="DEV",
                max_length=20,
                verbose_name="status",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="categories",
            field=models.ManyToManyField(related_name="tasks", to="tasks.category"),
        ),
    ]
