# Generated by Django 6.0 on 2026-01-02 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_category_alter_task_managers_alter_task_status_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="category",
            managers=[],
        ),
        migrations.AlterModelManagers(
            name="task",
            managers=[],
        ),
    ]
