# Generated by Django 6.0 on 2026-01-01 16:43

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[("MANAGER", "Manager"), ("REPORTEE", "Reportee")],
                max_length=50,
                null=True,
                verbose_name="primary role",
            ),
        ),
    ]
