# Generated by Django 6.0 on 2026-01-01 17:51

import apps.core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_user_managers_alter_user_role"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.core.models.SoftDeleteManager()),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
    ]
