# Generated by Django 6.0 on 2026-01-02 08:19

import apps.authentication.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_alter_user_managers_user_company"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.authentication.models.UserSoftDeleteManager()),
            ],
        ),
    ]
